services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todoappdb
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  # Todo Application Service
  todo-app:
    build: .
    container_name: todo-app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/todoappdb
      DB_USERNAME: todouser
      DB_PASSWORD: todopassword
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    networks:
      - todo-network

# Volumes for data persistence
volumes:
  mysql_data:
    driver: local

# Networks
networks:
  todo-network:
    driver: bridge